### ISSUE TITLE
Facebook-Plugin geht nicht

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#1]
Das Plugin, welches beim Aufrufen der Seite zum Liken der Fanpage einlädt, baut sich nicht auf:
![screen shot 2017-01-13 at 11 10 50](https://cloud.githubusercontent.com/assets/7487883/21926194/faacb3d0-d980-11e6-903e-492c760c4b0c.png)

**Comment by KennySchnett** [comment]
Sollte wieder funzen.
