### ISSUE TITLE
geofunn - Content einzelner Geofunn wird nicht angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#10]
![screen shot 2017-01-13 at 11 26 17](https://cloud.githubusercontent.com/assets/7487883/21926767/7427515a-d983-11e6-887d-05841ab50826.png)

Siehe auch #6

**Comment by KennySchnett** [comment]
Das war mein Sorgenkind :-D Nach der Fehlersuche stellte sich heraus, dass es an dem Google+ Counter liegt (das Problem hatten wir in der dokuhl Testumgebung auch). Der neue Server scheint alle CURL Operationen zu unterdrücken, weswegen uns die ganze Maschinerie um die Ohren geflogen ist, als er versucht hat den Like counter zu holen. Ich habe eine neue Routine, für die Interaktion mir dem Google Server, geschrieben, die auf eine Wordpress eigene Methode setzt, die nicht mehr unterdrückt wird und nebenbei noch etwas performanter/sicherer ist. Das selbe Problem mit der CURL Interaktion gab es bei #3 .
Läuft alles wieder!

**Comment by diplomod** [comment]
Super, danke. Was ist der Google+ Counter?

BTW: Es ist kriegsentscheidend, dass auch Google Analytics nahtlos übernommen wird. Ist das gewährleistet oder müssen wir da was aktiv machen?
