### ISSUE TITLE
Author wird im Artikel nicht angezeigt

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#18]
Im Artikel:
<img width="732" alt="screen shot 2017-02-02 at 08 39 32" src="https://cloud.githubusercontent.com/assets/7487883/22541000/e258387e-e923-11e6-8688-97355f9bad85.png">

Auf home geht es:
<img width="434" alt="screen shot 2017-02-02 at 08 39 39" src="https://cloud.githubusercontent.com/assets/7487883/22541008/ec3e346a-e923-11e6-80ec-6d15fd598b65.png">

Betrifft alle Artikel

**Comment by lukassiedel** [comment]
ist gefixed.

**Comment by diplomod** [comment]
Wow, super merci!
