### ISSUE TITLE
Newsletter-Signup-Form unten links lässt sich nicht schließen

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#2]
Das Formular zum Newsletter, welches unten Links bei erstmaligen Aufrufen der Seite auftaucht, lässt sich nicht schließen - da sollte ein "X" sein in der oberen rechten Ecke:

![screen shot 2017-01-13 at 11 11 48](https://cloud.githubusercontent.com/assets/7487883/21926247/3eecc7ce-d981-11e6-876f-484c190ebf4d.png)

**Comment by KennySchnett** [comment]
Sollte auch wieder gehen
