### ISSUE TITLE
Widgets in Sidebar gehen nicht

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#3]
Geobuzz, Mailchimp und Oilprice-Widget gehen nicht. Vermutlich eine fehlende Verlinkung?
Hab im Admin-Bereich nicht gleich gefunden, was das sein könnte, bin da überfragt.
![screen shot 2017-01-13 at 11 13 40](https://cloud.githubusercontent.com/assets/7487883/21926271/5a10efb2-d981-11e6-9cb8-c619e377c6ab.png)

**Comment by KennySchnett** [comment]
Geht wieder. Lag an der CURL Interaktion im GEOBUZZ Widget.
