### ISSUE TITLE
2nd sidebar fehlt komplett

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#5]
![screen shot 2017-01-13 at 11 16 46](https://cloud.githubusercontent.com/assets/7487883/21926383/ccb840f6-d981-11e6-9734-c0498e4bb8e2.png)

Kann es sein, dass hier die Bilder für die Banner, welche dort angezeigt werden sollten, nicht greifbar sind?
![screen shot 2017-01-13 at 11 16 46](https://cloud.githubusercontent.com/assets/7487883/21926400/dbcdc908-d981-11e6-8428-35cc5ea06b06.png)

**Comment by KennySchnett** [comment]
Ist wieder da und scrollt auch mit.
