### ISSUE TITLE
Content schiebt sich hinter Header (Safari)

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#7]
![screen shot 2017-01-13 at 11 21 50](https://cloud.githubusercontent.com/assets/7487883/21926584/b071ad78-d982-11e6-9f55-f6a8b9a28aff.png)

Im Chrome passt es

**Comment by KennySchnett** [comment]
Lag an admin Leiste, die da sein sollte. Jetzt ist sie wieder da. Wurde durch JS Fehler blokiert.
