### ISSUE TITLE
geofunn - Karte baut sich nicht auf

### ISSUE THREAD

**Issue by diplomod** [diplomod/projects-on-geonova.no#9]
Bei erstmaligem Aufrufen. Reload hilft auch nicht.
![screen shot 2017-01-13 at 11 26 58](https://cloud.githubusercontent.com/assets/7487883/21926708/417a4c76-d983-11e6-9d9a-0bff2889ce7c.png)
Geht erst wenn man auf "Geofunn på kartet" clickt.

**Comment by KennySchnett** [comment]
Zum Einen musste die Verlinkung gefixt werden. Die Karte wird durch einen Fehler in dem WP Snowfall Plugin, was es auf der Seite schneien lässt, blockiert. Habe keinen schnellen Fix gefunden, der sich lohnt umzusetzen. Hab das Plugin erstmal deaktiviert. Wird sowieso bald Frühling ;-) Jetzt läuft wieder alles.

**Comment by diplomod** [comment]
Ah - alles klar, passt. :)
